codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: main

coverage:
  precision: 2
  round: down
  range: "95...100"
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
        branches:
          - main
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
        branches:
          - main
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no