[project]
name = "fitbit-client"
version = "0.1.0"
authors = [
    { name = "Jon Stroop", email = "jsfitbit-client@jopast.io" },
]
description = "A Python client for the Fitbit API"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "Typing :: Typed"
]
dependencies = [
    "requests-oauthlib>=1.3.0",
]
license = "AGPL-3.0-only"
license-files = ["LICENSE"]


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
dev = [
    "black>=24.10.0",
    "isort>=5.13.2",
    "beautifulsoup4>=4.12.3",
]

[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312', 'py313']
preview = true
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
multi_line_output = 3
force_single_line = true
known_first_party = ["fitbit_client"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_sort_within_sections = true

[tool.pdm.scripts]
fmt = { composite = [
    "black --quiet .", 
    "isort . --only-modified"
] }