name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm install -G:all
        
    - name: Run tests with coverage
      run: |
        pdm run pytest --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5.4.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
  
  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm install -G:all
        
    - name: Check Black formatting
      run: |
        pdm run black --check
        
    - name: Check isort
      run: |
        pdm run isort --check
        
    - name: Check unused imports with autoflake
      run: |
        pdm run autoflake
  
  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm install -G:all
        
    - name: Run mypy
      run: |
        pdm run mypy
  
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm install -G:all
        
    - name: Check markdown formatting
      run: |
        echo "Markdown format checking temporarily disabled"
        exit 0

  # todo: https://github.com/ydah/mdformat-action
  
  # build:
  #   runs-on: ubuntu-latest
  #   needs: [test, format, type-check, docs]
    
  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v3
    
  #   - name: Set up Python 3.13
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: "3.13"
        
  #   - name: Install PDM
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pdm
        
  #   - name: Install dependencies
  #     run: |
  #       pdm install -G:all
        
  #   - name: Build package
  #     run: |
  #       pdm build
